version: "3"
services:
  web:
    build: .
    container_name: 361_project_django
    restart: unless-stopped
    volumes:
      - code:/code
      - gunicorn_logs:/gunicorn/logs
      - static:/code/static
      - media:/code/media
    env_file:
      - prod..env

  nginx:
    restart: always
    build: ./nginx/
    container_name: 361_project_django_nginx
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_logs:/code/logs
      - static:/code/static
      - media:/code/media
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    links:
      - web
    env_file:
      - prod..env

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --staging -d tascheduler.aalagna.com --email anthonyalagna1999@gmail.com
    env_file:
      - prod..env


volumes:
  code:
  gunicorn_logs:
  media:
  static:
  nginx_conf:
  nginx_logs:
  certbot_conf:
    external:
      name: certbot_conf
  certbot_www:
    external:
      name: certbot_www
