version: "3"
services:
  web:
    build: .
    container_name: 361_project_django
    restart: unless-stopped
    volumes:
      - code:/code
      - gunicorn_logs:/gunicorn/logs
      - static:/code/static
      - media:/code/media
    env_file:
      - prod.env
  nginx:
    restart: always
    build: ./nginx/
    container_name: 361_project_django_nginx
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_logs:/code/logs
      - static:/code/static
      - media:/code/media
    ports:
      - "8006:80"
    depends_on:
      - web
    links:
      - web
    env_file:
      - prod.env
volumes:
  code:
  gunicorn_logs:
  media:
  static:
  nginx_conf:
  nginx_logs:
