# Generated by Django 4.2 on 2023-04-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='course_id')),
                ('Course_Name', models.CharField(max_length=50)),
                ('Course_Code', models.CharField(max_length=50)),
                ('Course_isOnline', models.CharField(max_length=6)),
                ('Course_Location', models.CharField(max_length=50)),
                ('Course_begin', models.DateTimeField(auto_now_add=True)),
                ('Course_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='user_id')),
                ('User_Name', models.CharField(max_length=200)),
                ('User_Email', models.CharField(max_length=200)),
                ('User_Type', models.CharField(max_length=200)),
                ('User_Phone', models.CharField(max_length=200)),
                ('User_Address', models.TextField(max_length=500)),
                ('User_LogName', models.CharField(max_length=200)),
                ('User_LogPass', models.CharField(max_length=200)),
                ('User_isGrader', models.CharField(max_length=3)),
                ('User_begin', models.DateTimeField(auto_now_add=True)),
                ('User_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseToUser',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='section_id')),
                ('Sec_Name', models.CharField(max_length=200)),
                ('Sec_Location', models.CharField(max_length=200)),
                ('Sec_isOnline', models.CharField(max_length=7)),
                ('Sec_begin', models.DateTimeField(auto_now_add=True)),
                ('Sec_Updated', models.DateTimeField(auto_now=True)),
                ('Sec_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('Sec_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='User_SecAssigned',
            field=models.ManyToManyField(related_name='users', through='myapp.CourseToUser', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='coursetouser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
