# Generated by Django 4.2 on 2023-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isLoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
