# Generated by Django 4.2 on 2023-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_LogName',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pw_reset_token',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
