# Generated by Django 4.2 on 2023-04-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='Sec_isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_LogName',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_LogPass',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_isGrader',
            field=models.BooleanField(default=False),
        ),
    ]
