# Generated by Django 4.2 on 2023-05-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_city',
            new_name='city',
        ),
    ]
