# Generated by Django 4.2 on 2023-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
