# Generated by Django 4.2 on 2023-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="User_Email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="User_LogName",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=200, unique=True),
        ),
    ]
