# Generated by Django 4.1.7 on 2023-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_name_user_user_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Pos',
            field=models.CharField(max_length=2),
        ),
    ]
