# Generated by Django 4.2 on 2023-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Instructor',
            field=models.CharField(max_length=50),
        ),
    ]
