# Generated by Django 4.2 on 2023-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_user_email_remove_user_user_logname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw_reset_token',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
