# Generated by Django 4.2 on 2023-05-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_address_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='myapp.section'),
        ),
    ]
