# Generated by Django 4.2 on 2023-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_user_email_alter_user_user_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_SecAssigned',
            field=models.ManyToManyField(blank=True, related_name='users', through='myapp.CourseToUser', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_isGrader',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
