# Generated by Django 4.2 on 2023-05-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_pw_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course_isOnline',
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Instruction_Method',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
