# Generated by Django 4.2 on 2023-04-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_course_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.user')),
            ],
            bases=('myapp.user',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_Name',
            new_name='User_fName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_Type',
            new_name='User_lName',
        ),
        migrations.AddField(
            model_name='user',
            name='User_City',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Pos',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_SecAssigned',
            field=models.ManyToManyField(blank=True, related_name='users', through='myapp.CourseToUser', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_isGrader',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
