# Generated by Django 4.2 on 2023-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_supervisor_rename_user_name_user_user_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Pos',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
