# Generated by Django 4.2 on 2023-04-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_user_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
