# Generated by Django 4.2 on 2023-05-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_isloggedin'),
        ('myapp', '0005_remove_course_course_location'),
    ]

    operations = [
    ]
