# Generated by Django 4.1.7 on 2023-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_user_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Instructor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
