# Generated by Django 4.1.7 on 2023-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_course_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='user_id'),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
