# Generated by Django 4.1.7 on 2023-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='section_id'),
        ),
    ]
