# Generated by Django 4.1.7 on 2023-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='course_id'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='section_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='user_id'),
        ),
    ]
