name: Django Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p $HOME/.ssh/
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/private.key
          chmod 600 $HOME/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > $HOME/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: Deploy to server
        # don't run locally
        uses: appleboy/ssh-action@master
        env:
          HOME: ${{ env.HOME }}
          SSH_KEY_PATH: ${{ env.HOME }}/.ssh/private.key
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ env.SSH_KEY_PATH }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull ${{secrets.REPO_URL}}
            docker-compose down -v
            docker-compose up --build -d --remove-orphans --renew-anon-volumes --force-recreate
            ufw-docker allow 361_project_django_nginx
