name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
<<<<<<< HEAD
<<<<<<< HEAD
        python-version: [3.11]
=======
        python-version: [3.7, 3.8, 3.9]
>>>>>>> origin/HEAD
=======
        python-version: [3.7, 3.8, 3.9]
>>>>>>> bd588dac47f7f77a7d1c4576d720eea5602b4f2a

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
