name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - name: Restore state
        id: restore-state
        uses: actions/cache@v2
        with:
          key: state-${{ github.sha }}
          path: state.txt
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge main into branch
        if: steps.restore-state.outputs.cache-hit != 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B ${{ github.ref }}
          git merge --no-edit --no-ff ${{ github.event.pull_request.head.sha }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test tests/
